--- #YAML:1.0
name:               App-Bulkmail
version:            0.01
abstract:           Simple but flexible bulkmailer
author:
    - Peter Makholm <peter@makholm.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Slurp:  0
    Template:     0
    Test::More:   0
    YAML:         0
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/pmakholm/app-bulkmail-perl
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
